import { ChevronLeft, ChevronRight } from "lucide-react";
import Link from "next/link";

export function Pagination({ page, total, pageSize, pathname, params, pageSizes }: { page: number; total: number; pageSize: number; pathname: string; params: Record<string, string | undefined>; pageSizes?: number[] }) {
  const pages = Math.max(1, Math.ceil(total / pageSize));
  const href = (target: number, size = pageSize) => { const query = new URLSearchParams(); Object.entries(params).forEach(([key, value]) => { if (value) query.set(key, value); }); query.set("page", String(target)); if (pageSizes) query.set("size", String(size)); return `${pathname}?${query}`; };
  if (pages <= 1 && !pageSizes) return null;
  return <nav className="flex flex-wrap items-center justify-between gap-3 border-t border-[var(--border)] px-4 py-3" aria-label="分页"><span className="text-[12px] tabular text-[var(--muted-foreground)]">第 {Math.min(page, pages)} / {pages} 页 · 共 {total} 条</span><div className="flex items-center gap-2">{pageSizes && <details className="relative"><summary className="btn min-h-9 cursor-pointer list-none px-3 text-[12px]">{pageSize} 条/页</summary><div className="menu-popover absolute bottom-11 right-0 z-20 min-w-[110px] p-1">{pageSizes.map((size) => <Link key={size} className="menu-item" href={href(1, size)} aria-current={size === pageSize ? "true" : undefined}>{size} 条/页</Link>)}</div></details>}{page > 1 ? <Link className="btn icon-btn min-h-9 size-9" href={href(page - 1)} aria-label="上一页" title="上一页"><ChevronLeft size={16} /></Link> : <button className="btn icon-btn min-h-9 size-9" disabled aria-label="已是第一页"><ChevronLeft size={16} /></button>}{page < pages ? <Link className="btn icon-btn min-h-9 size-9" href={href(page + 1)} aria-label="下一页" title="下一页"><ChevronRight size={16} /></Link> : <button className="btn icon-btn min-h-9 size-9" disabled aria-label="已是最后一页"><ChevronRight size={16} /></button>}</div></nav>;
}
